config/routes.rb
Rails.application.routes.draw do



  resources :pages, only: [:show]


  # mount RedactorRails::Engine => '/redactor_rails'

  resources :locations, only: [:index, :show]
  resources :events, only: [:index, :show]
  resources :programs, only: [:index, :show]

  devise_for :users

  root to: 'home#index'

  get   'bomb'        => 'home#bomb', :as => :bomb
  get   'home/index'
  match 'preferences' => 'preferences#edit', :as => :preferences, via: [:get, :patch]

  namespace :admin do
    resources :users do
      get :undelete, on: :member
    end
    resources :programs do
      get :sendmail, on: :member
    end
    resources :events do
      get :copy, on: :member
      get :set_status, on: :member
    end
    resources :pages
    resources :contents
    resources :flyers
    resources :locations
  end

end

app/models/location.rb
class Location < ActiveRecord::Base
  has_many  :events

  validates :title, presence: true



  def twitter_link
    "https://twitter.com/#{self.twitter}"
  end
end

app/controllers/admin/locations_controller.rb
class Admin::LocationsController < Admin::AdminController
  before_action :set_location, only: [:show, :edit, :update, :destroy]

  respond_to :html

  before_action :authenticate_user!


  def index
    @locations = Location.all
    respond_with(@locations)
  end

  def show
    respond_with(@location)
  end

  def new
    @location = Location.new
    respond_with(@location)
  end

  def edit
  end

  def create
    @location = Location.new(location_params)
    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Page was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update

    respond_to do |format|
      if  @location.update(location_params)
       format.html { redirect_to admin_location_url(@location), notice: 'Location was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @location.destroy
    respond_to do |format|
      format.html { redirect_to admin_locations_url, notice: 'Location was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_location
      @location = Location.find(params[:id])
    end

    def location_params
      params.require(:location).permit(:title, :address, :zipcode, :city, :email, :web, :twitter, :lat, :lon, :shortext, :longtext)
    end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:show]

  respond_to :html


  def index
    redirect_to root_url
  end

  def show
    respond_with(@location)
  end

  private
    def set_location
      @location = Location.find(params[:id])
    end

end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/admin/locations/_form.html.haml
= simple_form_for([:admin,@location]) do |f|

  .row
    .large-12.columns
      = f.error_notification
      %h3
        = f.input :title, :label => "Title", :input_html => { :class => 'large'}

  .row.form-inputs
    .large-4.columns
      = f.input :address
      .row
        .column.small-2
          = f.input :zipcode
        .column.small-6
          = f.input :city
      = f.input :lat, :label => "Lat (not implemented yet)"
      = f.input :lon, :label => "Lat (not implemented yet)"
    .large-4.columns
      = f.input :email
      = f.input :web
      = f.input :twitter
    .large-4.columns
      = f.input :shortext, :input_html => { :class => '', :rows => 4}
      = f.input :longtext, :input_html => { :class => 'redactor', :rows => 8}

  .row
    .large-12.columns
      .form-actions
        = f.button :submit, {:class=>"button large"}

app/views/admin/locations/edit.html.haml
- content_for :title, "Locations"
.row
  .large-8.columns
    %h1 Location
  .large-4.columns.right
    = link_to admin_locations_path, :class => 'button' do
      %i.fi-list-thumbnails
      Index
    = link_to @location, :class => 'button' do
      %i.fi-eye
      Anzeigen
.row
  .large-12.columns
    = render 'form'

app/views/admin/locations/index.html.haml
- content_for :title, "Locations"
.row
  .large-9.columns
    %h1 Locations
  .large-3.columns.right
    = link_to new_admin_location_path, :class => 'button' do
      %i.fi-plus
      Location anlegen
.row
  .large-12.columns{:role => "content"}
    .table-responsive
      %table.table.table-striped.table-bordered.table-hover
        %thead
          %tr
            %th Title
            %th Shortext
            %th Address/Zipcode/City
            %th Email/Web/Twitter
            %th Lat/Lon

            %th
            %th
            %th

        %tbody
          - @locations.each do |location|
            %tr
              %td
                %h3
                  = link_to location do
                    = location.title
              %td= location.shortext
              %td
                = location.address
                %br
                = location.zipcode
                = location.city
              %td
                %i.fi-mail
                = link_to location.email do
                  = location.email
                %br
                %i.fi-web
                = link_to location.web do
                  = location.web
                %br
                - if location.twitter.present?
                  %i.fi-social-twitter
                  = link_to location.twitter_link do
                    = location.twitter
              %td
                = location.lat
                = location.lon

              %td
                = link_to admin_location_path(location), :class=>"button tiny" do
                  %i.fi-eye
                  Anzeigen
              %td
                = link_to edit_admin_location_path(location), :class=>"button tiny" do
                  %i.fi-pencil
                  Bearbeiten
              %td
                = link_to  admin_location_path(location), :data => { confirm: 'Wirklich löschen?' }, :method => :delete, :class=>"button tiny alert" do
                  %i.fi-x
                  Löschen

app/views/admin/locations/new.html.haml
- content_for :title, "Locations"
.row
  .large-8.columns
    %h1 Location
  .large-4.columns.right
    = link_to admin_locations_path, :class => 'button' do
      %i.fi-list-thumbnails
      Index
.row
  .large-12.columns
    = render 'form'

app/views/admin/locations/show.html.haml
- content_for :title, @location.title

.row
  .large-7.columns{:role => "content"}
    %h1 Location
  .large-5.columns.right
    = link_to admin_locations_path, :class => 'button' do
      %i.fi-list-thumbnails
      Index
    = link_to new_admin_location_path, :class => 'button' do
      %i.fi-plus
      Location anlegen
    = link_to edit_admin_location_path(@location), :class => 'button' do
      %i.fi-pencil
      Bearbeiten
.row
  .large-6.columns{:role => "content"}
    .panel
      %h2
        %strong=@location.title
      %p
        #{@location.address}, #{@location.zipcode} #{@location.city}
      %p
        - if @location.web.present?
          %i.fi-web
          = link_to @location.web do
            = @location.web

        - if @location.email.present?
          \|
          %i.fi-mail
          = link_to @location.email do
            = @location.email
        - if @location.twitter.present?
          \|
          %i.fi-social-twitter
          = link_to @location.twitter_link do
            = @location.twitter
      - if @location.shortext.present?
        %p
          %i.fi-info.fi-21
          = @location.shortext