config/routes.rb
Rails.application.routes.draw do



  resources :pages, only: [:show]


  # mount RedactorRails::Engine => '/redactor_rails'

  resources :locations, only: [:index, :show]
  resources :events, only: [:index, :show]
  resources :programs, only: [:index, :show]

  devise_for :users

  root to: 'home#index'

  get   'bomb'        => 'home#bomb', :as => :bomb
  get   'home/index'
  match 'preferences' => 'preferences#edit', :as => :preferences, via: [:get, :patch]

  namespace :admin do
    resources :users do
      get :undelete, on: :member
    end
    resources :programs do
      get :sendmail, on: :member
    end
    resources :events do
      get :copy, on: :member
      get :set_status, on: :member
    end
    resources :pages
    resources :contents
    resources :flyers
    resources :locations
  end

end

app/models/event.rb
class Event < ActiveRecord::Base

  after_initialize :set_defaults, unless: :persisted?
  # The set_defaults will only work if the object is new

  mount_uploader :image, ImageUploader

  belongs_to  :location
  belongs_to  :program

  require 'date'

  validates :title, presence: true


  scope :published, -> { where status: 'Published' }

  scope :with_status, lambda { |name|
    where('status = ?', name)
  }

  # ["Programm","Neues im zakk","Und sonst?"]
  scope :with_ptype, lambda { |name|
    where('ptype = ?', name)
  }


  def set_defaults
    self.status  ||= 'draft'
  end


  def starttime
    "#{self.startdate.hour}.#{sprintf '%02d', self.startdate.min}"
  end

  def startday
    "#{self.startdate.day}.#{self.startdate.month}"
  end

  def startweekday

    day = {0 => "Sontag",
            1 => "Montag",
            2 => "Dienstag",
            3 => "Mittwoch",
            4 => "Donnerstag",
            5 => "Freitag",
            6 => "Samstag"}
    day[self.startdate.wday]
  end

end

app/controllers/admin/events_controller.rb
class Admin::EventsController < Admin::AdminController
  before_action :set_event, only: [:show, :edit, :update, :destroy, :set_status]

  layout 'admin'

  before_action :authenticate_user!

  respond_to :html

  def index

    # TODO: show only events not older than 1 month
    @events = Event.all
    @grid = EventsGrid.new(params[:events_grid]) do |scope|
      scope.page(params[:page])
    end
    respond_with(@events)
  end

  def show
    redirect_to event_path(@event)
  end

  def new
    @event = Event.new

    @selected_location = helpers.default_location_id
    @selected_program = helpers.current_program_id
    @selected_status = helpers.default_status
    @selected_ptype = helpers.default_ptype

    require 'uri'

    if params[:program]
      @selected_program = URI.unescape(params[:program])
    end

    if params[:ptype]
      @selected_ptype = params[:ptype].to_i
    end

    respond_with(@event)
  end

  def edit

    if @event.location.present?
      @selected_location = @event.location_id
    else
      @selected_location = ''
    end
    @selected_program = @event.program_id
    @selected_status = @event.status
    @selected_ptype = @event.ptype

  end

  def create
    @event = Event.new(event_params)
    @event.save
    flash[:notice] = "Event saved"
    if params[:commit] == "Event erstellen"
      respond_with(@event)
    else
      respond_with(@event, :status => :created, :location => new_admin_event_path)
    end
  end

  def copy

    @old_event = Event.find(params[:id])
    @event = @old_event.dup
    @event.save!

    if @event.location.present?
      @selected_location = @event.location_id
    else
      @selected_location = ''
    end
    @selected_program = @event.program_id
    @selected_status = @event.status
    @selected_ptype = @event.ptype

    redirect_to edit_admin_event_url( @event ), notice: "Kopie dieses Event angelegt."

  end

  def update
    @event.update(event_params)
    flash[:notice] = "Event updated"
    respond_with(@event)
  end

  def destroy
    @event.destroy
    flash[:notice] = "Event deleted"
    respond_to do |format|
      format.html { redirect_to admin_events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  def set_status
    @switch_id    = "event_switch_#{@event.id}"

    if @event.status == 'Published'
      @event.status = 'Draft'
    else
      @event.status = 'Published'
    end
    @event.save!

    respond_to do |format|
      format.js
    end

  end

  private
    def set_event
      @event = Event.find(params[:id])
    end

    def event_params
      params.require(:event).permit(:title, :shortext, :longtext, :startdate, :enddate, :location_id, :link, :label, :organizer, :organizerlink, :image, :ptype, :status, :program_id, :locationtext, :remove_image)
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show]

  respond_to :html


  def index
    if helpers.current_program && helpers.current_program.id
      redirect_to program_url(helpers.current_program.id)
    else
      redirect_to root_url
    end
  end

  def show
    @pages = Page.where(published: true).where(in_menu: true)

    if current_user || @event.status == 'Published'
      respond_to do |format|
        format.html { render :show }
      end
    else
      redirect_to root_url, notice: 'Event is not publically available :('
    end
  end

  private

  def set_event
    @event = Event.find(params[:id])
  end

end

app/helpers/events_helper.rb
module EventsHelper

  def location_for_select
    Location.all.order(:title).map do |p|
      [p.title, p.id]
    end
  end

  def default_location_id
    d = Location.where("title LIKE ?","%zakk%").first
    if d
      d.id
    else
      nil
    end
  end

  def program_for_select
    Program.all.order( 'id DESC' ).map do |p|
      if p.current
        ["#{p.title} (current)", p.id]
      else
        ["#{p.title}", p.id]
      end
    end
  end

  def current_program_id
    d = Program.where('current = ?', true).first
    if d.present?
      d.id
    else
      nil
    end
  end


  def ptype_for_select
    [["Programm","0"],["Neues im zakk","1"],["Und sonst?","2"]]
  end

  def default_ptype
    "0"
  end

  def status_for_select
    # TODO: if we need a three-step workflow: ["Draft","Ready","Published"]
    ["Draft","Published"]
  end

  def default_status
    status_for_select[0]
  end

  def smart_date_display(startdate,enddate)
    if !enddate
      "#{I18n.l(startdate, format: '%A')[0..1]} #{startdate.strftime("%d.%m.%y, %H:%M")}"
    elsif startdate > enddate
      "#{I18n.l(startdate, format: '%A')[0..1]} #{startdate.strftime("%d.%m.%y, %H:%M")}"
    elsif  startdate == enddate
      "#{I18n.l(startdate, format: '%A')[0..1]} #{startdate.strftime("%d.%m.%y, %H:%M")}"
    elsif startdate.to_date == enddate.to_date
      "#{I18n.l(startdate, format: '%A')[0..1]} #{startdate.strftime("%d.%m.%y, %H:%M")} ‒ #{enddate.strftime("%H:%M")}"
    else
      "#{I18n.l(startdate, format: '%A')[0..1]} #{startdate.strftime("%d.%m.%y, %H:%M")} ‒ #{I18n.l(enddate, format: '%A')[0..1]} #{enddate.strftime("%d.%m.%y, %H:%M")}"
    end

  end

end

app/views/admin/events/_form.html.haml
= simple_form_for([:admin,@event]) do |f|
  .row
    .large-12.columns
      = f.error_notification
  .row
    .large-7.columns

      .form-inputs
        .row
          .column.small-6
            = f.input :status, :collection => status_for_select, :label => "Status", :selected => @selected_status, :input_html => { :class => '' }
          .column.small-6
            &nbsp;
        = f.input :program_id, :collection => program_for_select, :label => "Program", :selected => @selected_program, :input_html => { :class => '' }
        %small
        = f.input :ptype, :collection => ptype_for_select, :label => "Type", :selected => @selected_ptype, :input_html => { :class => '' }
    .large-5.columns
      %p
        &nbsp;
        = f.input :image, as: :file
        - if @event.image.present?
          = image_tag @event.image.thumb.url
          %br
          = f.check_box :remove_image
          Bild löschen
  .row
    .large-7.columns
      = f.input :title, :input_html => { :class => 'input-large large'}
      .row
        .column.small-6
          = f.input :startdate, as: :fdatetimepicker
        .column.small-6
          = f.input :enddate, as: :fdatetimepicker
      = f.input :shortext, :input_html => { :class => '', :rows => 4}
      = f.input :longtext, :input_html => { :class => '',  :rows => 10}


    .large-5.columns
      %hr
      = f.input :location_id, :collection => location_for_select, :label => "Location auswählen", :include_blank => "--", :selected => @selected_location, :input_html => { :class => '' }
      %p
        ODER
      = f.input :locationtext, :label => "Name der Location"
      = f.input :link, :placeholder => "http://", :label => "Website der Location"
      %hr
      = f.input :organizer, :label => "Organizer"
      = f.input :organizerlink, :placeholder => "http://", :label => "Website des/der Organizers"
      %hr
      = f.input :label
  .row
    .large-12.columns

      .form-actions
        = f.button :submit, :class=>"button large"
        - if current_page?(:action => 'new')
          = f.button :submit, :class=>"button large", :value=>"Event erstellen und nächsten eingeben"

app/views/admin/events/_show_mini.html.haml
- public = public || false

- klass = "panel event event_mini"
- if Event.status == 'Published'
  - klass += " event_published"
- else
  - klass += " event_draft"



%div{:class=>"#{klass}"}
  - if ( can? :create, Event )
    .metas
      .metas_label
        - if Event.status == 'Published'
          %span.label.label_status.label_status_published
            = Event.status
        - else
          %span.label.label_status.label_status_draft
            = Event.status
      .metas_label
        %span.label.label_ptype
          = ptypes[Event.ptype.to_i]
  %p
    - if Event.startdate
      = smart_date_display(Event.startdate,Event.enddate)
    - if Event.location
      \|
      = Event.location.title
  %p
    - if Event.image.url
      %img{:src=>"#{Event.image.small_thumb.url}"}
  %h4
    = link_to "#{Event.title}", event
    - if (can? :edit, Event) && (public != true)
      = link_to edit_admin_event_path(event), :class=>"tiny" do
        %i.fi-pencil
      - if Event.status != 'published'
        = link_to edit_admin_event_path(event), :class=>"tiny" do
          %i.fi-eye

  - if Event.shortext.present?
    %div
      = Event.shortext

app/views/admin/events/edit.html.haml
- content_for :title, "Edit #{@event.title}"


.row
  .large-8.columns
    %h1 Edit Event
  .large-4.columns.right
    = link_to admin_events_path, :class => 'button' do
      %i.fi-list-thumbnails
      Index
    = link_to @event, :class => 'button' do
      %i.fi-eye
      Anzeigen
.row
  .large-8.columns
    = render 'form'
  .large-4.columns
    &nbsp;

app/views/admin/events/index.html.haml
- content_for :title, "Events"

.row
  .large-9.columns{:role => "content"}
    %h1 Event
  .large-3.columns.right
    = link_to new_admin_event_path, :class => 'button' do
      %i.fi-plus
      Neuen Event anlegen

.row
  .large-12.columns
    = datagrid_form_for @grid, :method => :get, :url => events_path
.row
  .large-12.columns
    = will_paginate(@grid.assets)
.row
  .large-12.columns{:role => "content"}
    = datagrid_table @grid

app/views/admin/events/new.html.haml
- content_for :title, "Event"


.row
  .large-4.columns
    %h1 New Event
  .large-4.columns.text-right
    = link_to admin_events_path, :class => 'button' do
      %i.fi-list-thumbnails
      Index
  .large-4.columns
    &nbsp;
.row
  .large-8.columns
    = render 'form'
  .large-4.columns
    &nbsp;

app/views/admin/events/set_status.js.erb
<% if @text %>
  $("#<%= @switch_id %>").find('.event-switch-message').removeClass("hide");
  $("#<%= @switch_id %>").find('.event-switch-message').text("<%= @text %>");
<% else %>
  $("#<%= @switch_id %>").find('.event-switch-message').addClass("hide");
  <% if @event.status == 'Published' %>
    $("#<%= @switch_id %>").parents('tr').find('td').removeClass("event_draft").addClass("event_published");
    $("#<%= @switch_id %>").parents('div.panel').removeClass("event_draft").addClass("event_published");
    $("#<%= @switch_id %>").removeClass("event_draft").addClass("event_published");
    $("#<%= @switch_id %>").find('.event-status-draft').removeClass("event-status-anchor-active").addClass("event-status-anchor");
    $("#<%= @switch_id %>").find('.event-status-published').removeClass("event-status-anchor").addClass("event-status-anchor-active");
  <% else %>
    $("#<%= @switch_id %>").parents('tr').find('td').removeClass("event_published").addClass("event_draft");
    $("#<%= @switch_id %>").parents('div.panel').removeClass("event_published").addClass("event_draft");
    $("#<%= @switch_id %>").removeClass("event_published").addClass("event_draft");
    $("#<%= @switch_id %>").find('.event-status-published').removeClass("event-status-anchor-active").addClass("event-status-anchor");
    $("#<%= @switch_id %>").find('.event-status-draft').removeClass("event-status-anchor").addClass("event-status-anchor-active");
  <% end %>
<% end %>

app/views/admin/events/show.html.haml
- content_for :title, "Event \"#{@event.title}\""

- if ( can? :create, Event )
  .row
    .large-9.columns{:role => "content"}
      &nbsp;
    .large-3.columns.right
      = link_to admin_events_path, :class => 'button tiny' do
        %i.fi-list-thumbnails
        Index
      = link_to new_admin_event_path, :class => 'button tiny' do
        %i.fi-plus
        Event anlegen
      = link_to edit_admin_event_path(@event), :class => 'button tiny' do
        %i.fi-pencil
        Bearbeiten

= render partial: "/partials/header"

.row.panel
  .large-6.text-left.columns{:role => "content"}
    %p
      - if @event.image.url
        %img{:src=>"#{@event.image.url}"}
      - else
        = image_tag('zakk_pattern3.png')

  .large-6.columns
    %p
      - if @event.startdate
        %i.fi-calendar
        = smart_date_display(@event.startdate,@event.enddate)
        - if @event.location
          &nbsp;|&nbsp;
          %i.fi-home
          =@event.location.title
    %h2
      %strong
        = @event.title
      \|
      = @event.shortext
    %p= sanitize @event.longtext.html_safe

    %p
      - if !@event.link.blank?
        - if @event.link =~ /http[s]?:\/\//
          - linktext = @event.link.gsub(/https?:\/\//,"")
          = link_to "#{escape_once(linktext)}", escape_once(@event.link)
        - else
          = link_to "http://"+@event.link, "#{@event.link}"
    %hr
    %p
      - if !@event.label.blank?
        %dt Label:
        %dd= @event.label
      - if !@event.organizer.blank?
        %dt Organizer:
        %dd
          = @event.organizer
          = @event.organizerlink
    %hr
    .row
      .large-12.columns
        %span.label
          = @event.status
        \/
        %span.label
          = ptypes[@event.ptype.to_i]
        \/
        %small
          - if @event.program
            - if ( can? :create, Event )
              = link_to "#{@event.program.title}", admin_program_url(@event.program)
            - else
              =@event.program.title
    - if @event.location
      %hr
      %p.location
        %h4=@event.location.title
        %p
          #{@event.location.address}, #{@event.location.zipcode}, #{@event.location.city}
          %br
          - if @event.location.web
            %i.fi-web.fi-21
            = link_to @event.location.web do
              = @event.location.web

          - if @event.location.email
            &nbsp;&nbsp;|&nbsp;
            %i.fi-mail.fi-21
            = link_to @event.location.email do
              = @event.location.email
          - if @event.location.twitter.present?
            &nbsp;&nbsp;|&nbsp;
            %i.fi-social-twitter.fi-21
            = link_to @event.location.twitter_link do
              = @event.location.twitter
          %br
          %p
            %i.fi-info.fi-21
            = @event.location.shortext