config/routes.rb
Rails.application.routes.draw do



  resources :pages, only: [:show]


  # mount RedactorRails::Engine => '/redactor_rails'

  resources :locations, only: [:index, :show]
  resources :events, only: [:index, :show]
  resources :programs, only: [:index, :show]

  devise_for :users

  root to: 'home#index'

  get   'bomb'        => 'home#bomb', :as => :bomb
  get   'home/index'
  match 'preferences' => 'preferences#edit', :as => :preferences, via: [:get, :patch]

  namespace :admin do
    resources :users do
      get :undelete, on: :member
    end
    resources :programs do
      get :sendmail, on: :member
    end
    resources :events do
      get :copy, on: :member
      get :set_status, on: :member
    end
    resources :pages
    resources :contents
    resources :flyers
    resources :locations
  end

end

app/models/program.rb
class Program < ActiveRecord::Base

  before_save :set_published
  before_save :falsify_all

	mount_uploader :image, ImageUploader
	mount_uploader :backgroundimage, ImageUploader

  has_many :events

  validates :title, presence: true,
                    uniqueness: { case_sensitive: false }


  def falsify_all
    if self.current
      self.class.where('id != ? and current', self.id).update_all("current = false")
    end
  end


  def set_published
    if self.current == true
      self.published = true
    else
      # self.published = false
    end
    true
  end

end

app/controllers/admin/programs_controller.rb
class Admin::ProgramsController < Admin::AdminController
  before_action :set_program, only: [:show, :edit, :update, :destroy]

  layout 'admin'

  before_action :authenticate_user!

  # GET /programs
  # GET /programs.json
  def index
    @programs = Program.all.order( 'id DESC' )
  end

  # GET /programs/1
  # GET /programs/1.json
  def show
  end

  # GET /programs/new
  def new
    if current_program && current_program.title
      @program = current_program.dup
      if @program.title
        @program.title = @program.title+' (copy)'
      end
      @program.current = false
      flash[:notice] = 'Die Werte im Formular sind eine Kopie des aktuellen Programms. (Bilder können nicht mitkopiert werden.)'
    else
      @program = Program.new
    end
    render :new
  end

  # GET /programs/1/edit
  def edit
  end

  # POST /programs
  # POST /programs.json
  def create
    @program = Program.new(program_params)

    respond_to do |format|
      if @program.save
        format.html { redirect_to admin_programs_url, notice: 'Program was successfully created.' }
        format.json { render :show, status: :created, location: @program }
      else
        format.html { render :new }
        format.json { render json: @program.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /programs/1
  # PATCH/PUT /programs/1.json
  def update
    respond_to do |format|
      if @program.update(program_params)
        format.html { redirect_to admin_programs_url, notice: 'Program was successfully updated.' }
        format.json { render :show, status: :ok, location: @program }
      else
        format.html { render :edit }
        format.json { render json: @program.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /programs/1
  # DELETE /programs/1.json
  def destroy
    @program.destroy
    respond_to do |format|
      format.html { redirect_to admin_programs_url, notice: 'Program was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  def sendmail
    @program = Program.find_by_id(params[:id])
    if @program
      ProgramsMailer.program_email(@program,current_user.email).deliver_now
      redirect_to admin_program_url(@program), notice: 'Programmvorschau wurde versendet'
    else
      redirect_to root_url, notice: 'Ein Problem ist aufgetreten'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_program
      @program = Program.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def program_params
      params.require(:program).permit(:title, :description, :published, :backgroundcolor, :textcolor1, :textcolor2, :backgroundimage, :remove_backgroundimage, :backgroundimage_credit, :backgroundimage_credit_link, :backgroundimage_display, :image, :remove_image, :image_credit, :image_credit_link, :current)
    end
end

app/controllers/programs_controller.rb
class ProgramsController < ApplicationController
  before_action :set_program, only: [:show]

  # GET /programs
  # GET /programs.json
  def index
    if current_program && current_program.id
      redirect_to program_url(current_program.id)
    end
  end

  # GET /programs/1
  # GET /programs/1.json
  def show
    if current_user || ( current_program && ( params[:id] == "current" ))
      respond_to do |format|
        format.xml { render layout: false }
        format.json { render layout: false }
        format.html { render :show }
      end
    else
      redirect_to root_url, notice: 'Program is not publically available :('
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_program
      if current_program && ( params[:id] == "current" )
        @program = current_program
      else
        @program = Program.find(params[:id])
      end
    end

end

app/helpers/admin/programs_helper.rb
module Admin::ProgramsHelper
end

app/helpers/programs_helper.rb
module ProgramsHelper

  def backgroundimage_display_for_select
    [["Bildschirmgröße","cover"],["Kacheln","inherit"]]
  end

end

app/views/admin/programs/_form.html.haml
.row
  .large-12.columns
    = simple_form_for([:admin,@program]) do |f|
      = f.error_notification
      .row.form-inputs
        .large-8.columns
          .row
            .large-12.columns
              = f.input :title, :input_html => { :class => 'large'}
          .row
            .large-6.columns
              = f.input :description
              .row
                .large-6.columns
                  = f.input :current
                .large-6.columns
                  = f.input :published
            .large-6.columns
              = f.input :backgroundcolor, as: :minicolors
              = f.input :textcolor1, as: :minicolors
              = f.input :textcolor2, as: :minicolors
          .row
            .large-12.columns
              %hr
          .row
            .large-6.columns
              = f.input :image, as: :file
              - if @program.image.present?
                = image_tag @program.image.medium_thumb.url
                %br
                = f.check_box :remove_image
                Bild löschen
              .hide
                = f.input :image_credit
                = f.input :image_credit_link

            .large-6.columns
              = f.input :backgroundimage, as: :file
              - if @program.backgroundimage.present?
                = image_tag @program.backgroundimage.medium_thumb.url
                %br
                = f.check_box :remove_backgroundimage
                Bild löschen
              = f.input :backgroundimage_credit
              = f.input :backgroundimage_credit_link, :input_html => { :placeholder => 'http://'}
              = f.input :backgroundimage_display, :collection => backgroundimage_display_for_select, :include_blank => false, :input_html => { :class => '' }
        .large-4.columns#preview
          %h3 Colors preview:
          .panel
            %h1
              %strong zakk
              klubraum
          .panel
            %p 06.01.2017, 22:00
            %h3 Ungesundes Mittelmaß
            %p punks'n'pandas, queers'n'beers, nerds'n'birds.
      .form-actions
        = f.button :submit, {:class=>"button large"}

app/views/admin/programs/edit.html.haml
- content_for :head do
  = render partial: '/partials/custom_styles', locals: {program: @program}

.row
  .large-8.columns
    %h1 program
  .large-4.columns.right
    = link_to admin_programs_path, :class => 'button' do
      %i.fi-list-thumbnails
      Index
    = link_to [:admin, @program], :class => 'button' do
      %i.fi-eye
      Anzeigen
.row
  .large-8.columns
    = render 'form'
  .large-4.columns
    &nbsp;

app/views/admin/programs/index.html.haml
.row
  .large-9.columns{:role => "content"}
    %h1 Programme
  .large-3.columns.right
    = link_to new_admin_program_path, :class => 'button' do
      %i.fi-plus
      Neues Programm anlegen
.row
  .large-12.columns{:role => "content"}
    .table-responsive
      %table.table.table-striped.table-bordered.table-hover
        %thead
          %tr
            %th Image
            %th Backgroundimage
            %th Title
            %th Published?
            %th Events

            %th
            %th

        %tbody
          - @programs.each do |program|
            - klass = ''
            - if program.current
              - klass += 'current '
            - if program.published
              - klass += 'published'
            %tr{:class=>klass}
              %td
                - if program.image.url
                  <img src="#{program.image.medium_thumb.url}">
                - elsif program.published
                  #{image_tag('zakk_pattern1.png', :class => "medium_thumb")}
                - else
                  #{image_tag('zakk_pattern2.png', :class => "medium_thumb")}
              %td
                - if program.backgroundimage.url
                  - if program.backgroundimage_display == 'cover'
                    - style = "background-image: url(#{program.backgroundimage.medium_thumb.url}); background-size: 100vw; background-position: -50vw -50vw;"
                  - else
                    - style = "background-image: url(#{program.backgroundimage.medium_thumb.url}); background-size: 50px;"
                - elsif program.published
                  - style = "background-image: url(#{image_url('zakk_pattern1.png')}); background-size: cover"
                - else
                  - style = "background-image: url(#{image_url('zakk_pattern2.png')}); background-size: cover"
                %div.backgroundimage_preview{:style=>style}
                  .panel
                    %h3{:style=>"color: #{program.textcolor2}"}
                      %strong{:style=>"color: #{program.textcolor1}"} zakk
                      klubraum
              %td{:width=>'400'}
                %h1
                  = link_to admin_program_path(program) do
                    = program.title
                  - if program.current
                    %span.label
                      CURRENT
                - if program.description.present?
                  %div
                    = program.description

              %td
                - if program.published
                  %i.fi-check.fi-32
                - else
                  %i.fi-x.fi-32
              %td= program.events.count

              %td
                = link_to edit_admin_program_path(program), :class=>"button tiny", :data => { :turbolinks=> "false" } do
                  %i.fi-pencil.fi-21
                  %br
                  Bearbeiten
              %td
                = link_to [:admin,program], :data => { confirm: 'Wirklich löschen?' }, :method => :delete, :class=>"button tiny alert" do
                  %i.fi-x.fi-21
                  %br
                  Löschen

app/views/admin/programs/new.html.haml
.row
  .large-8.columns
    %h1 program
  .large-4.columns.right
    = link_to admin_programs_path, :class => 'button tiny' do
      %i.fi-list-thumbnails
      Index
.row
  .large-8.columns
    = render 'form'
  .large-4.columns
    &nbsp;

app/views/admin/programs/show.html.haml
- content_for :head do
  = render partial: '/partials/custom_styles', locals: {program: @program}


.row
  .large-7.columns
    %h1
      = @program.title
      - if @program.current
        %span.label
          CURRENT
    %h3= @program.description
  .large-5.columns.right
    = link_to admin_programs_path, :class => 'button' do
      %i.fi-list-thumbnails
      Index
    = link_to new_admin_program_path, :class => 'button' do
      %i.fi-plus
      Program anlegen
    = link_to edit_admin_program_path(@program), :class => 'button' do
      %i.fi-pencil
      Bearbeiten
.row
  .large-2.columns
    &nbsp;
  .large-6.columns{:role => "content"}
    %h3.panel
      das zakk
      %strong Programm
    %ol
      - @program.events.with_ptype('0').order(:startdate).each do |event|
        %li
          = render partial: '/events/show_mini', locals: {event: event}
      %li
        = link_to new_admin_event_path(:ptype => '0',:program => @program.id), :class => 'button tiny' do
          %i.fi-plus
          Event anlegen
    %h3.panel
      Und
      %strong sonst
      ?
    %ol
      - @program.events.with_ptype('2').order(:startdate).each do |event|
        %li
          = render partial: '/events/show_mini', locals: {event: event}
      %li
        = link_to new_admin_event_path(:ptype => '2',:program => @program.id), :class => 'button tiny' do
          %i.fi-plus
          Event anlegen

    .row
      .large-12.columns.text-center
        - if @program.image_credit.present? || @program.backgroundimage_credit.present?
          %hr
        - if @program.image_credit.present?
          %p
            Credit for the program image:
            %br
            %strong
              =  @program.image_credit
        - if @program.backgroundimage_credit.present?
          %p
            Credit for the program background image:
            %br
            %strong
              =  @program.backgroundimage_credit
    .row
      .large-12.columns.text-center
        %hr
        - if !@program.current
          %button{:class=>"button disabled", :disabled => "disabled"} Make this the current program (TODO)
        - else
          %i.fi-check.fi-32
          %br
          This is the current program
        %br
        - if !@program.published
          %button{:class=>"button disabled", :disabled => "disabled"} Make this program public (TODO)
        - else
          %i.fi-check.fi-32
          %br
          This program is published
    .row
      .large-12.columns
        %hr
    .row
      .large-4.columns
        = link_to program_path(:id => @program.id, :format => 'json'), :class => 'button' do
          Render this page as JSON (Serialized)
      .large-4.columns
        = link_to program_path(:id => @program.id, :format => 'xml'), :class => 'button' do
          Export to XML (InDesign)
      .large-4.columns
        = link_to sendmail_admin_program_path(:id => @program.id, :user => current_user), :class=>"button" do
          Send as E-Mail to #{current_user.email}
  .large-4.columns
    &nbsp;